CREATE DATABASE PROJETO_POUSADA
GO

USE PROJETO_POUSADA
GO

CREATE SCHEMA [config]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [config].[TB_MENU_ITEM](
	[ID_MENU_ITEM] [int] IDENTITY(1,1) NOT NULL,
	[ID_MENU_ITEM_SUPERIOR] [int] NULL,
	[NM_ITEM] [varchar](100) NOT NULL,
	[NM_CONTROLLER] [varchar](50) NULL,
	[NM_ACTION] [varchar](50) NULL,
	[CLASS_ICON] [varchar](50) NULL,
	[FL_STATUS] [bit] NOT NULL,
	[NM_AREA] [varchar](50) NULL,
	[LNK_REDIRECIONAMENTO] [varchar](255) NULL,
	[FL_REDIRECIONAMENTO_EXTERNO] [bit] NOT NULL,
	[FL_ABRIR_MODAL] [bit] NOT NULL,
	[ID_CONTROL_MODAL] [varchar](50) NULL,
	[FL_HEADER] [bit] NOT NULL,
 CONSTRAINT [PK_TB_MENU] PRIMARY KEY CLUSTERED 
(
	[ID_MENU_ITEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [config].[TB_PARAMETRO](
	[ID_PARAMETRO] [int] IDENTITY(1,1) NOT NULL,
	[DS_PARAMETRO] [varchar](255) NOT NULL,
	[DS_OBSERVACAO] [varchar](255) NULL,
	[VALOR] [varchar](255) NULL,
 CONSTRAINT [PK_TB_PARAMETRO] PRIMARY KEY CLUSTERED 
(
	[ID_PARAMETRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [config].[TB_PARAMETRO_GRUPO](
	[ID_PARAMETRO_GRUPO] [int] IDENTITY(1,1) NOT NULL,
	[ID_PARAMETRO] [int] NOT NULL,
	[ID_GRUPO] [int] NOT NULL,
 CONSTRAINT [PK_TB_PARAMETRO_GRUPO] PRIMARY KEY CLUSTERED 
(
	[ID_PARAMETRO_GRUPO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY],
 CONSTRAINT [UK_TB_PARAMETRO_GRUPO_ID_PARAMETRO_ID_GRUPO] UNIQUE NONCLUSTERED 
(
	[ID_PARAMETRO] ASC,
	[ID_GRUPO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [config].[TB_PERMISSAO_ITEM_MENU]    Script Date: 28/02/2023 11:13:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [config].[TB_PERMISSAO_ITEM_MENU](
	[ID_PERMISSAO_ITEM_MENU] [int] IDENTITY(1,1) NOT NULL,
	[ID_MENU_ITEM] [int] NOT NULL,
	[ID_GRUPO] [int] NOT NULL,
 CONSTRAINT [PK_TB_PERMISSAO_ITEM_MENU] PRIMARY KEY CLUSTERED 
(
	[ID_PERMISSAO_ITEM_MENU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [config].[TB_MENU_ITEM] ADD  CONSTRAINT [DF_TB_MENU_FL_STATUS]  DEFAULT ((1)) FOR [FL_STATUS]
GO
ALTER TABLE [config].[TB_MENU_ITEM] ADD  DEFAULT ((0)) FOR [FL_REDIRECIONAMENTO_EXTERNO]
GO
ALTER TABLE [config].[TB_MENU_ITEM] ADD  DEFAULT ((0)) FOR [FL_ABRIR_MODAL]
GO
ALTER TABLE [config].[TB_MENU_ITEM] ADD  CONSTRAINT [DF_TB_MENU_ITEM_FL_HEADER]  DEFAULT ((0)) FOR [FL_HEADER]
GO
ALTER TABLE [config].[TB_MENU_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_TB_MENU_ID_MENU_SUPERIOR] FOREIGN KEY([ID_MENU_ITEM_SUPERIOR])
REFERENCES [config].[TB_MENU_ITEM] ([ID_MENU_ITEM])
GO
ALTER TABLE [config].[TB_MENU_ITEM] CHECK CONSTRAINT [FK_TB_MENU_ID_MENU_SUPERIOR]
GO
ALTER TABLE [config].[TB_PARAMETRO_GRUPO]  WITH CHECK ADD  CONSTRAINT [FK_TB_PARAMETRO_GRUPO_ID_PARAMETRO] FOREIGN KEY([ID_PARAMETRO])
REFERENCES [config].[TB_PARAMETRO] ([ID_PARAMETRO])
GO
ALTER TABLE [config].[TB_PARAMETRO_GRUPO] CHECK CONSTRAINT [FK_TB_PARAMETRO_GRUPO_ID_PARAMETRO]
GO
ALTER TABLE [config].[TB_PERMISSAO_ITEM_MENU]  WITH CHECK ADD  CONSTRAINT [FK_TB_PERMISSAO_ITEM_MENU_ID_MENU_ITEM] FOREIGN KEY([ID_MENU_ITEM])
REFERENCES [config].[TB_MENU_ITEM] ([ID_MENU_ITEM])
GO
ALTER TABLE [config].[TB_PERMISSAO_ITEM_MENU] CHECK CONSTRAINT [FK_TB_PERMISSAO_ITEM_MENU_ID_MENU_ITEM]
GO

CREATE SCHEMA cadastro

CREATE TABLE cadastro.TB_CLIENTE(

ID_CLIENTE INT NOT NULL IDENTITY (1,1),
NM_CLIENTE VARCHAR (400) NOT NULL,
DT_NASCIMENTO DATE NOT NULL,
NR_CPF VARCHAR (11) NOT NULL,
DT_CADASTRO DATETIME NOT NULL,
NR_RG VARCHAR (20),
FL_ATIVO BIT NOT NULL CONSTRAINT DF_TB_CLIENTE_FL_ATIVO DEFAULT 1

CONSTRAINT PK_TB_CLIENTE_ID_CLIENTE PRIMARY KEY (ID_CLIENTE)
)
GO

CREATE TABLE cadastro.TB_TIPO_ENDERECO(

ID_TIPO_ENDERECO INT NOT NULL IDENTITY(1,1),
DS_TIPO_ENDERECO VARCHAR (200) NOT NULL,
FL_ATIVO BIT NOT NULL CONSTRAINT DF_TB_TIPO_ENDERECO_FL_ATIVO DEFAULT 1

CONSTRAINT PK_TB_TIPO_ENDERECO_ID_TIPO_ENDERECO PRIMARY KEY(ID_TIPO_ENDERECO)
)
GO

INSERT INTO cadastro.TB_TIPO_ENDERECO (DS_TIPO_TELEFONE) VALUES('Residencial')
GO
INSERT INTO cadastro.TB_TIPO_ENDERECO (DS_TIPO_TELEFONE) VALUES('Comercial')
GO

CREATE TABLE cadastro.TB_ENDERECO(

ID_ENDERECO INT NOT NULL IDENTITY(1,1),
ID_CLIENTE INT NOT NULL,
ID_TIPO_ENDERECO INT NOT NULL,
NM_LOGRADOURO VARCHAR (400) NOT NULL,
NR_LOGRADORO VARCHAR (20),
NR_CEP VARCHAR (7) NOT NULL,
NM_BAIRRO VARCHAR (400),
DT_CADASTRO DATETIME NOT NULL,
FL_ATIVO BIT NOT NULL CONSTRAINT DF_TB_ENDERECO_FL_ATIVO DEFAULT 1

CONSTRAINT PK_TB_ENDERECO_ID_ENDERECO PRIMARY KEY (ID_ENDERECO),
CONSTRAINT FK_TB_ENDERECO_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES cadastro.TB_CLIENTE,
CONSTRAINT FK_TB_ENDERECO_ID_TIPO_ENDERECO FOREIGN KEY (ID_TIPO_ENDERECO) REFERENCES cadastro.TB_TIPO_ENDERECO
)
GO

CREATE TABLE cadastro.TB_TIPO_TELEFONE(

ID_TIPO_TELEFONE INT NOT NULL IDENTITY(1,1),
DS_TELEFONE VARCHAR(200) NOT NULL,
FL_ATIVO BIT NOT NULL CONSTRAINT DF_TB_TIPO_TELEFONE_FL_ATIVO DEFAULT 1

CONSTRAINT PK_TB_TIPO_TELEFONE_ID_TIPO_TELEFONE PRIMARY KEY(ID_TIPO_TELEFONE)
)
GO

INSERT INTO cadastro.TB_TIPO_TELEFONE (DS_TELEFONE) VALUES('Celular')
GO
INSERT INTO cadastro.TB_TIPO_TELEFONE (DS_TELEFONE) VALUES('Residencial')
GO
INSERT INTO cadastro.TB_TIPO_TELEFONE (DS_TELEFONE) VALUES('Comercial')
GO

CREATE TABLE cadastro.TB_TELEFONE(

ID_TELEFONE INT NOT NULL IDENTITY(1,1),
ID_CLIENTE INT NOT NULL,
ID_TIPO_TELEFONE INT NOT NULL,
NR_DDD VARCHAR (2) NOT NULL,
NR_TELEFONE VARCHAR(9) NOT NULL,
DT_CADASTRO DATETIME NOT NULL,
FL_ATIVO BIT NOT NULL CONSTRAINT DF_TB_TELEFONE_FL_ATIVO DEFAULT 1


CONSTRAINT PK_TB_TELEFONE_ID_TELEFONE PRIMARY KEY(ID_TELEFONE),
CONSTRAINT FK_TB_TELEFONE_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES cadastro.TB_CLIENTE,
CONSTRAINT FK_TB_TELEFONE_ID_TIPO_TELEFONE FOREIGN KEY (ID_TIPO_TELEFONE) REFERENCES cadastro.TB_TIPO_TELEFONE
)
GO

CREATE TABLE config.TB_USUARIO(

ID_USUARIO INT NOT NULL IDENTITY(1,1),
NM_USUARIO VARCHAR(300) NOT NULL,
NR_CPF VARCHAR (11) NOT NULL,
DT_NASCIMENTO DATE NOT NULL,
DS_EMAIL VARCHAR(300),
DT_CADASTRO DATETIME NOT NULL,
DS_SENHA VARCHAR(30) NOT NULL,
FL_ATIVO BIT NOT NULL CONSTRAINT DF_TB_USUARIO_FL_ATIVO DEFAULT 1

CONSTRAINT PK_TB_USUARIO_ID_USUARIO PRIMARY KEY (ID_USUARIO)

)

CREATE SCHEMA [historico]
GO
/****** Object:  Table [historico].[TB_LOG]    Script Date: 09/03/2023 12:18:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [historico].[TB_LOG](
	[ID_LOG] [int] IDENTITY(1,1) NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
	[ESCOPO] [varchar](500) NOT NULL,
	[ID_REGISTRO] [int] NOT NULL,
	[TP_OPERACAO] [varchar](20) NOT NULL,
	[DT_CADASTRO] [datetime] NULL,
	[VALORES_ANTIGOS] [varchar](max) NULL,
	[VALORES_NOVOS] [varchar](max) NULL,
	[PROPRIEDADES_ALTERADAS] [varchar](max) NULL,
 CONSTRAINT [PK_TB_LOG_ID_LOG] PRIMARY KEY CLUSTERED 
(
	[ID_LOG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [historico].[TB_LOG] ADD  CONSTRAINT [DF_TB_LOG_DT_CADASTRO]  DEFAULT (getdate()) FOR [DT_CADASTRO]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Código interno gerado automaticamente para identificação do registro' , @level0type=N'SCHEMA',@level0name=N'historico', @level1type=N'TABLE',@level1name=N'TB_LOG', @level2type=N'COLUMN',@level2name=N'ID_LOG'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Código do usuário' , @level0type=N'SCHEMA',@level0name=N'historico', @level1type=N'TABLE',@level1name=N'TB_LOG', @level2type=N'COLUMN',@level2name=N'ID_USUARIO'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Nome da entidade onde está sendo realizada a operação' , @level0type=N'SCHEMA',@level0name=N'historico', @level1type=N'TABLE',@level1name=N'TB_LOG', @level2type=N'COLUMN',@level2name=N'ESCOPO'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Código do registro na entidade/tabela' , @level0type=N'SCHEMA',@level0name=N'historico', @level1type=N'TABLE',@level1name=N'TB_LOG', @level2type=N'COLUMN',@level2name=N'ID_REGISTRO'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Tipo de operação que está sendo realizada' , @level0type=N'SCHEMA',@level0name=N'historico', @level1type=N'TABLE',@level1name=N'TB_LOG', @level2type=N'COLUMN',@level2name=N'TP_OPERACAO'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Data da operação' , @level0type=N'SCHEMA',@level0name=N'historico', @level1type=N'TABLE',@level1name=N'TB_LOG', @level2type=N'COLUMN',@level2name=N'DT_CADASTRO'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Valores antigos das propriedades/campos' , @level0type=N'SCHEMA',@level0name=N'historico', @level1type=N'TABLE',@level1name=N'TB_LOG', @level2type=N'COLUMN',@level2name=N'VALORES_ANTIGOS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Novos valores das propriedade/campos' , @level0type=N'SCHEMA',@level0name=N'historico', @level1type=N'TABLE',@level1name=N'TB_LOG', @level2type=N'COLUMN',@level2name=N'VALORES_NOVOS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Propriedades que foram alteradas' , @level0type=N'SCHEMA',@level0name=N'historico', @level1type=N'TABLE',@level1name=N'TB_LOG', @level2type=N'COLUMN',@level2name=N'PROPRIEDADES_ALTERADAS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Armazena os logs das operações realizadas nas entidades do sistema (Insert/Update/Delete)' , @level0type=N'SCHEMA',@level0name=N'historico', @level1type=N'TABLE',@level1name=N'TB_LOG'
GO
